"""outreach tables

Revision ID: 6717f028feff
Revises: dde6e9f78c59
Create Date: 2026-08-29 21:58:06.052233

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6717f028feff'
down_revision: str | Sequence[str] | None = 'dde6e9f78c59'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('provider_id', sa.String(length=120), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('is_connection', sa.Boolean(), nullable=True),
    sa.Column('can_send_inmail', sa.Boolean(), nullable=True),
    sa.Column('status_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_url')
    )
    op.create_table('outreach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('note_body', sa.Text(), nullable=True),
    sa.Column('drafted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('invited_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('provider_ref', sa.String(length=120), nullable=True),
    sa.Column('failure', sa.Text(), nullable=True),
    sa.Column('last_state_change', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'contact_id', name='uq_outreach_job_contact')
    )
    with op.batch_alter_table('outreach', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outreach_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outreach', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreach_job_id'))
        batch_op.drop_index(batch_op.f('ix_outreach_contact_id'))

    op.drop_table('outreach')
    op.drop_table('contacts')
    # ### end Alembic commands ###
