"""job poster

Revision ID: 90c0b9caf29f
Revises: 6717f028feff
Create Date: 2026-08-31 17:32:52.567352

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '90c0b9caf29f'
down_revision: str | Sequence[str] | None = '6717f028feff'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('poster_profile_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('poster_profile_url')
        batch_op.drop_column('poster_name')

    # ### end Alembic commands ###
