"""initial schema

Revision ID: bce70775e801
Revises: 
Create Date: 2026-08-20 03:06:41.184085

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bce70775e801'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('domain', sa.String(length=300), nullable=True),
    sa.Column('yc_batch', sa.String(length=40), nullable=True),
    sa.Column('yc_slug', sa.String(length=200), nullable=True),
    sa.Column('yc_tags', sa.JSON(), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('last_probed_at', sa.DateTime(), nullable=True),
    sa.Column('probe_status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', 'domain', name='uq_company_identity')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_normalized_name'), ['normalized_name'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_key', sa.String(length=60), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=True),
    sa.Column('raw_fetched', sa.Integer(), nullable=False),
    sa.Column('new_jobs', sa.Integer(), nullable=False),
    sa.Column('updated_jobs', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_run_key'), ['run_key'], unique=False)

    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('discovered_via', sa.String(length=30), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('next_fetch_at', sa.DateTime(), nullable=True),
    sa.Column('last_job_count', sa.Integer(), nullable=True),
    sa.Column('consecutive_errors', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'token', name='uq_board_provider_token')
    )
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boards_next_fetch_at'), ['next_fetch_at'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('title_normalized', sa.String(length=500), nullable=False),
    sa.Column('seniority', sa.String(length=20), nullable=True),
    sa.Column('role_family', sa.String(length=20), nullable=True),
    sa.Column('location_raw', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('remote_type', sa.String(length=10), nullable=False),
    sa.Column('tz_min_overlap_h', sa.Float(), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=8), nullable=True),
    sa.Column('salary_period', sa.String(length=10), nullable=True),
    sa.Column('salary_is_stated', sa.Boolean(), nullable=False),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('description_md', sa.Text(), nullable=True),
    sa.Column('description_lang', sa.String(length=8), nullable=True),
    sa.Column('description_en_md', sa.Text(), nullable=True),
    sa.Column('jd_completeness', sa.String(length=10), nullable=False),
    sa.Column('jd_source', sa.String(length=20), nullable=True),
    sa.Column('jd_extracted_at', sa.DateTime(), nullable=True),
    sa.Column('jd_quality_score', sa.Float(), nullable=True),
    sa.Column('description_hash', sa.String(length=32), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('apply_url', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('canonical_job_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('missed_runs', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('repost_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['canonical_job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_job_source_external')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_job_market_active_seen', ['market', 'is_active', 'first_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_board_id'), ['board_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_canonical_job_id'), ['canonical_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_description_hash'), ['description_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_title_normalized'), ['title_normalized'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('folder_path', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('last_status_change', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_job_id'), ['job_id'], unique=False)

    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.String(length=30), nullable=False),
    sa.Column('deterministic_pass', sa.Boolean(), nullable=False),
    sa.Column('deterministic_notes', sa.JSON(), nullable=True),
    sa.Column('llm_score', sa.Float(), nullable=True),
    sa.Column('llm_reasoning', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.String(length=60), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'profile', name='uq_score_job_profile')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_job_id'))

    op.drop_table('scores')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_job_id'))

    op.drop_table('applications')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_title_normalized'))
        batch_op.drop_index(batch_op.f('ix_jobs_description_hash'))
        batch_op.drop_index(batch_op.f('ix_jobs_canonical_job_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_board_id'))
        batch_op.drop_index('ix_job_market_active_seen')

    op.drop_table('jobs')
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boards_next_fetch_at'))

    op.drop_table('boards')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_run_key'))

    op.drop_table('runs')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_companies_domain'))

    op.drop_table('companies')
    # ### end Alembic commands ###
