"""employment type

Revision ID: dde6e9f78c59
Revises: f6b3865b7911
Create Date: 2026-08-20 14:37:36.016686

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dde6e9f78c59'
down_revision: str | Sequence[str] | None = 'f6b3865b7911'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employment_type', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_jobs_employment_type'), ['employment_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_employment_type'))
        batch_op.drop_column('employment_type')

    # ### end Alembic commands ###
